DROP TABLE IF EXISTS VEH_DATA;
CREATE TABLE VEH_DATA
(
    VIN               VARCHAR(17)  NOT NULL PRIMARY KEY,
    OWNER_NAME        VARCHAR(50)  NOT NULL,
    PURCHASE_DATE     DATE         NOT NULL,
    LAST_SERVICE_DATE DATE,
    MODEL             VARCHAR(50)  NOT NULL,
    COLOR             VARCHAR(10)  NOT NULL,
    IS_TCU_ENABLED    VARCHAR(1)   NOT NULL,
    CREATE_USER       VARCHAR(100) NOT NULL,
    CREATE_S          DATE         NOT NULL,
    LAST_UPDT_USER    VARCHAR(100) NOT NULL,
    LAST_UPDT_S       DATE         NOT NULL
);

DROP TABLE IF EXISTS FTR_DATA;
CREATE TABLE FTR_DATA
(
    FTR_CODE       VARCHAR(10)  NOT NULL PRIMARY KEY,
    FTR_DESC       VARCHAR(100) NOT NULL,
    CREATE_USER    VARCHAR(100) NOT NULL,
    CREATE_S       DATE         NOT NULL,
    LAST_UPDT_USER VARCHAR(100) NOT NULL,
    LAST_UPDT_S    DATE         NOT NULL
);

DROP TABLE IF EXISTS VEH_FTR_DATA;
CREATE TABLE VEH_FTR_DATA
(
    VEH_FTR_D      BIGINT       auto_increment,
    VIN            VARCHAR(17)  NOT NULL,
    FTR_CODE       VARCHAR(10)  NOT NULL,
    CREATE_USER    VARCHAR(100) NOT NULL,
    CREATE_S       DATE         NOT NULL,
    LAST_UPDT_USER VARCHAR(100) NOT NULL,
    LAST_UPDT_S    DATE         NOT NULL,
    foreign key (VIN) references VEH_DATA (VIN),
    foreign key (FTR_CODE) references FTR_DATA (FTR_CODE)
);

DROP TABLE IF EXISTS VEH_LOCK_STATUS;
CREATE TABLE VEH_LOCK_STATUS (
    VIN VARCHAR(17) NOT NULL PRIMARY KEY,
    IS_LOCKED VARCHAR(1) NOT NULL,
    CREATE_USER    VARCHAR(100) NOT NULL,
    CREATE_S       DATE         NOT NULL,
    LAST_UPDT_USER VARCHAR(100) NOT NULL,
    LAST_UPDT_S    DATE         NOT NULL
);
